name: image_picker
description: A new flutter plugin project.

flutter:
  plugin:
    androidPackage: io.flutter.plugins.imagepicker
    pluginClass: ImagePickerPlugin

dependencies:
  flutter:
    sdk: flutter
